FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    git curl wget python libglib2.0-dev clang

ARG DEPOT_TOOLS=/opt/depot_tools
ARG DOCKER_WORKDIR=/app/AlphaRTC/

RUN git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ${DEPOT_TOOLS}
ENV PATH="${DEPOT_TOOLS}/:${PATH}"

WORKDIR "${DOCKER_WORKDIR}/"
