FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    libx11-6 libgomp1 python3 python3-pip

# Use pip install for torch and numpy inside docker.
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY lib /usr/lib/

COPY bin /usr/bin/

COPY pylib /usr/lib/python3/dist-packages/

