FROM ubuntu:18.04
FROM python:3.9

# Removed libjpeg8-dev
RUN apt-get update && apt-get install -y \
    libx11-6 libgomp1 zlib1g-dev python python3-pip


# Use pip install for torch and numpy inside docker.
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY lib /usr/lib/

COPY bin /usr/bin/

COPY pylib /usr/lib/python3/dist-packages/

